# -*- coding: utf-8 -*-
"""TrueValue APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPkfRox9G_vJBM-9DI7Aes604Hm4K_O_
"""

!pip install streamlit --quiet

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px
import numpy as np

# Set page config
st.set_page_config(page_title="Quant Valuation Tool", layout="wide")

st.title("📈 Statistical Valuation Dashboard")
st.write("Compare current valuation multiples against historical distributions to identify over/undervaluation.")

# Sidebar Inputs
ticker_symbol = st.sidebar.text_input("Enter Ticker (e.g., AAPL, MSFT, TSLA)", "AAPL")
lookback_years = st.sidebar.slider("Historical Lookback (Years)", 1, 10, 5)

@st.cache_data
def get_valuation_data(ticker, years):
    # Fetch ticker data
    tk = yf.Ticker(ticker)
    hist = tk.history(period=f"{years}y")

    # Get fundamental data
    info = tk.info
    current_pe = info.get('trailingPE')
    eps = info.get('trailingEps')

    if not current_pe or not eps:
        return None, None, None

    # Calculate historical "Proxy P/E"
    # (Price / Current EPS) to see how the market valued this specific earning power
    hist['Proxy_PE'] = hist['Close'] / eps
    return hist, current_pe, info.get('shortName')

data, current_pe, company_name = get_valuation_data(ticker_symbol, lookback_years)

if data is not None:
    st.header(f"{company_name} ({ticker_symbol})")

    # Metrics calculation
    hist_pe = data['Proxy_PE'].dropna()
    percentile = (hist_pe < current_pe).mean() * 100
    mean_pe = hist_pe.mean()
    std_pe = hist_pe.std()
    z_score = (current_pe - mean_pe) / std_pe

    # Display Metrics
    col1, col2, col3 = st.columns(3)
    col1.metric("Current P/E", f"{current_pe:.2f}")
    col2.metric("Historical Percentile", f"{percentile:.1f}%")
    col3.metric("Z-Score (Sigma)", f"{z_score:.2f}")

    # Economic Interpretation Logic
    st.subheader("Economic Interpretation")
    if percentile > 90:
        st.error(f"⚠️ **Highly Overvalued:** The current P/E is higher than {percentile:.1f}% of its {lookback_years}-year history.")
    elif percentile < 10:
        st.success(f"✅ **Highly Undervalued:** The current P/E is lower than {100-percentile:.1f}% of its {lookback_years}-year history.")
    else:
        st.info("⚖️ **Fair Value:** The stock is trading within its normal historical range.")

    # Histogram Visualization
    st.subheader("P/E Ratio Distribution")
    fig = px.histogram(data, x="Proxy_PE", nbins=50,
                       title=f"Historical P/E Distribution ({lookback_years} Years)",
                       labels={'Proxy_PE': 'P/E Ratio'},
                       color_discrete_sequence=['#636EFA'])

    # Add a vertical line for the current P/E
    fig.add_vline(x=current_pe, line_width=3, line_dash="dash", line_color="red",
                  annotation_text="Current P/E", annotation_position="top right")

    st.plotly_chart(fig, use_container_width=True)

    # Historical Trend Chart
    st.subheader("Valuation Trend Over Time")
    st.line_chart(data['Proxy_PE'])

else:
    st.error("Could not retrieve data for this ticker. Please check the symbol and try again.")